verbose: false
instrumentation:
    root: .
    extensions:
        - .js
    default-excludes: true
    excludes: ['test.js', 'test/**/*.js', '**/node_modules/**']
    compact: false
reporting:
    root: ./coverage/tmp
    print: summary
    reports:
        - lcov
    dir: ./coverage
    report-config:
      json:
        file: coverage.json
    watermarks:
        statements: [80, 95]
        lines: [80, 95]
        functions: [80, 95]
        branches: [80, 95]
